#ifndef CONFIG_H
#define CONFIG_H

#define DELAY_NANOSEC_PER_FRAME (100000000L)

enum {
    SCREEN_WIDTH = 7,
    SCREEN_HEIGHT = 10,

    DEFAULT_SCORE = 10,

    DRAWING_DELAY_FRAME_COUNT = 10,
};

#endif /* CONFIG_H */